services:
  db:
    image: postgres:16-alpine
    container_name: wms-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wms_db
    ports:
      - "5432:5432"
    volumes:
      - wms_pg_data:/var/lib/postgresql/data

volumes:
  wms_pg_data: